#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0

#define TAPPING_FORCE_HOLD

#define MK_COMBINED

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 10
#define NO_ALT_REPEAT_KEY

// Charybdis-specific settings
#define CHARYBDIS_CONFIG_SYNC // Sync sensor settings between hands
#define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_ENABLE
#define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_TIMEOUT_MS 1000
#define CHARYBDIS_AUTO_POINTER_LAYER_TRIGGER_THRESHOLD 1
#define CHARYBDIS_MINIMUM_SNIPING_DPI 50
